name: compile-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: gcc
      run: g++ SimulAncient_func.cpp atomic_fq.cpp -lz
