name: make-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [Ubuntulatest,Ubuntu1804]
        include:
          - name: Ubuntulatest
            os: ubuntu-latest
            compiler: clang
          - name: Ubuntu1804
            os: ubuntu-18.04
            compiler: [clang, gcc]
  
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update;sudo apt-get install libcurl4-openssl-dev samtools
    - name: prepare and compile htslib
      run: git clone --branch=develop --recursive https://github.com/samtools/htslib.git;cd htslib; make;cd ..;
    - name: Compile NGSNGS using HTSSRC
      run: export HTSSRC=`pwd`/htslib; make
    - name: Run test script
      run: make test
