name: make-test

on:
  push:
    branches: [ master, rahdev ]
  pull_request:
    branches: [ master, rahdev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-latest ]
        compiler: [ clang, gcc ]
  
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update;sudo apt-get install libcurl4-openssl-dev samtools
    - name: prepare and compile htslib
      run: git clone --branch=develop --recursive https://github.com/samtools/htslib.git;cd htslib; make;cd ..;
    - name: Compile NGSNGS using HTSSRC
      run: export HTSSRC=`pwd`/htslib; make
    - name: Run test script
      run: |
      make test
      if [ $? -ne 0 ]; then
        echo "Failing"
      exit 1
      fi
