name: make-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04,ubuntu-latest,macos-latest]
        compiler: [clang, gcc]
  
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        if ${{runner.os}} == 'Linux';
          sudo apt-get install libcurl4-openssl-dev
        elif ${{runner.os}} == 'macOS';
          brew install openssl curl
    - name: prepare htslib
      run: git clone --branch=develop --recursive git://github.com/samtools/htslib.git;cd htslib; make;cd ..;
    - name: make
      run: export HTSSRC=`pwd`/htslib; make
    - name: make
      run: make
